### ISSUE TITLE
Basic Usage

### ISSUE THREAD

**Issue by wamiq-reyaz** [zju3dv/NeuMesh#1]
Hey!

Thanks for the code release. I was trying to get code to run on an Ubuntu 20.04 machine with CUDA 11.1, Python 3.8 and Pytorch 1.8.0.

I compiled FRNN and built the environment. I downloaded the data from the NeuS Google Drive. But this is the error that I get. Not sure what I need to do

`python -m render --config configs/neumesh_dtu_scan63.yaml   --load_pt ./checkpoints/dtu_scan63/latest.pt --camera_path spiral --num_views 90 --background 1 --dataset_split entire --test_frame 24 --spiral_rad 1.2
=> Parse extra configs:  []
=> Use cuda devices: [0]
NeuMesh distance method frnn
geometry_dim: 32, input_ch_fg: 160
color_dim: 32, input_ch_ft: 160
input_d_dim: 1, input_view_dim: 3, input_ch_d: 17, input_ch_view: 27, input_ch_pts: 177, input_ch_color: 204
2022-08-08 16:11:31,608-rk0-render.py#285:=> Use ckpt:./checkpoints/dtu_scan63/latest.pt
Traceback (most recent call last):
  File "/home/parawr/anaconda3/envs/neumesh/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/parawr/anaconda3/envs/neumesh/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/parawr/Projects/adobe/neumesh/render.py", line 327, in <module>
    main_function(config)
  File "/home/parawr/Projects/adobe/neumesh/render.py", line 289, in main_function
    render_function(args, model, render_kwargs_test, render_fn, ckpt_file)
  File "/home/parawr/Projects/adobe/neumesh/render.py", line 102, in render_function
    dataset = get_data(args, downscale=args.downscale)
  File "/home/parawr/Projects/adobe/neumesh/dataio/__init__.py", line 36, in get_data
    dataset = SceneDataset(**cfgs)
  File "/home/parawr/Projects/adobe/neumesh/dataio/DTU.py", line 26, in __init__
    assert os.path.exists(data_dir), "Data directory is empty"
AssertionError: Data directory is empty

`

Any clue as to what might be wrong?

**Comment by chobao** [comment]
Do you specify the `data_dir` in the `configs/neumesh_dtu_scan63.yaml` before evaluation.

**Comment by wamiq-reyaz** [comment]
Whoopsie!

Missed that. Thanks a bunch.
